name = "backend"

workers_dev = true
compatibility_date = "2025-06-02"

main = "src/index.js"

[[d1_databases]]
binding = "MANPROD_DB"
database_name = "manajemen_produk"
database_id = "32392545-5117-4990-8c37-a0b8b4458d4a"
